### ISSUE TITLE
nexus.libreplan.dev is down (503)

### ISSUE THREAD

**Issue by tramseyer** [LibrePlan/libreplan#1942]

**Comment by kwoot** [comment]
Thanks! Will look at it asap!

**Comment by kwoot** [comment]
Should be fixed now.

**Comment by tramseyer** [comment]
Thanks, its working again.

**Comment by tramseyer** [comment]
For backup purposes, I have created a repo with the files on the server: https://github.com/tramseyer/thirdparty-libreplan16
Its contents could be served on a simple webserver and "https://nexus.libreplan.dev/repository/thirdparty-libreplan16/" in pom.xml be replaced locally if it were to be down for longer times.

**Comment by kwoot** [comment]
Yes, well I made a snafu and did a manual systemctl stop nexus last week. Sorry. Having said that, a backup is always a good thing! Maybe it would be more logical to back them up to a repo within the LibrePlan GitHub project. Also because other people, knowing about library injection attacks will not trust your repo as they don't know you. So, for the time being I suggest wel let the current nexus do it's work. As soon as I have some time I will make a backup on a LP project repo. Good idea?

**Comment by tramseyer** [comment]
> Yes, well I made a snafu and did a manual systemctl stop nexus last week. Sorry. Having said that, a backup is always a good thing! Maybe it would be more logical to back them up to a repo within the LibrePlan GitHub project. Also because other people, knowing about library injection attacks will not trust your repo as they don't know you. So, for the time being I suggest wel let the current nexus do it's work. As soon as I have some time I will make a backup on a LP project repo. Good idea?

Yes, this is a good idea. Thanks.
